/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Passage {
    id: string;
    content: string;
    wordCount: bigint;
    difficulty: bigint;
    category: string;
}
export interface Exam {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: Variant_hindi_bilingual_english;
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
}
export interface TypingResult {
    wpm: bigint;
    username: string;
    errors: bigint;
    language: string;
    timestamp: Time;
    examId: string;
    sessionId: string;
    timeTaken: bigint;
    examName: string;
    passed: boolean;
    accuracy: bigint;
}
export interface CallerUserProfile {
    name: string;
}
export interface UserProfile {
    username: string;
    createdAt: Time;
    securityQuestion: string;
    securityAnswer: string;
    passwordHash: string;
}
export interface LiveSessionPublic {
    startTime: Time;
    participants: Array<TypingResult>;
    timeLimit: bigint;
    isActive: boolean;
    examId: string;
    roomId: string;
    examName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_hindi_bilingual_english {
    hindi = "hindi",
    bilingual = "bilingual",
    english = "english"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createLiveSession(token: string, examId: string, examName: string, timeLimit: bigint): Promise<string>;
    finishLiveSession(token: string, roomId: string, username: string, wpm: bigint, accuracy: bigint, errors: bigint, timeTaken: bigint): Promise<void>;
    getActiveLiveSessions(): Promise<Array<LiveSessionPublic>>;
    getAllExams(): Promise<Array<Exam>>;
    getAllPassages(): Promise<Array<Passage>>;
    getCallerUserProfile(): Promise<CallerUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUserProfile(token: string): Promise<UserProfile>;
    getExam(examId: string): Promise<Exam>;
    getExamResults(examId: string): Promise<Array<TypingResult>>;
    getLeaderboard(): Promise<Array<TypingResult>>;
    getLiveSessionState(roomId: string): Promise<LiveSessionPublic>;
    getMyResults(token: string): Promise<Array<TypingResult>>;
    getPassage(passageId: string): Promise<Passage>;
    getPassagesByCategory(category: string): Promise<Array<Passage>>;
    getSessionResult(sessionId: string): Promise<TypingResult>;
    getUserProfile(user: Principal): Promise<CallerUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinLiveSession(token: string, roomId: string, username: string): Promise<boolean>;
    login(username: string, passwordHash: string): Promise<string>;
    registerUser(username: string, passwordHash: string, securityQuestion: string, securityAnswer: string): Promise<boolean>;
    resetPassword(username: string, securityAnswer: string, newPasswordHash: string): Promise<boolean>;
    saveCallerUserProfile(profile: CallerUserProfile): Promise<void>;
    submitResult(token: string, sessionId: string, examId: string, examName: string, wpm: bigint, accuracy: bigint, errors: bigint, timeTaken: bigint, passed: boolean, language: string): Promise<void>;
    updateProgress(token: string, roomId: string, username: string, wpm: bigint, accuracy: bigint, wordsTyped: bigint): Promise<void>;
    verifySession(token: string): Promise<boolean>;
}
import type { CallerUserProfile as _CallerUserProfile, Exam as _Exam, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createLiveSession(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLiveSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLiveSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async finishLiveSession(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishLiveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishLiveSession(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getActiveLiveSessions(): Promise<Array<LiveSessionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveLiveSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveLiveSessions();
            return result;
        }
    }
    async getAllExams(): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExams();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExams();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPassages(): Promise<Array<Passage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPassages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPassages();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<CallerUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserProfile(arg0: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserProfile(arg0);
            return result;
        }
    }
    async getExam(arg0: string): Promise<Exam> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_Exam_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_Exam_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamResults(arg0: string): Promise<Array<TypingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamResults(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<TypingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLiveSessionState(arg0: string): Promise<LiveSessionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveSessionState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveSessionState(arg0);
            return result;
        }
    }
    async getMyResults(arg0: string): Promise<Array<TypingResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResults(arg0);
            return result;
        }
    }
    async getPassage(arg0: string): Promise<Passage> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassage(arg0);
            return result;
        }
    }
    async getPassagesByCategory(arg0: string): Promise<Array<Passage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassagesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassagesByCategory(arg0);
            return result;
        }
    }
    async getSessionResult(arg0: string): Promise<TypingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionResult(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<CallerUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinLiveSession(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinLiveSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinLiveSession(arg0, arg1, arg2);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CallerUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitResult(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: boolean, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateProgress(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgress(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgress(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async verifySession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySession(arg0);
            return result;
        }
    }
}
function from_candid_Exam_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exam): Exam {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallerUserProfile]): CallerUserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: {
        hindi: null;
    } | {
        bilingual: null;
    } | {
        english: null;
    };
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
}): {
    minAccuracy: bigint;
    name: string;
    description: string;
    language: Variant_hindi_bilingual_english;
    requiredWPM: bigint;
    timeLimitMinutes: bigint;
    category: string;
    authority: string;
    officialWebsite: string;
} {
    return {
        minAccuracy: value.minAccuracy,
        name: value.name,
        description: value.description,
        language: from_candid_variant_n6(_uploadFile, _downloadFile, value.language),
        requiredWPM: value.requiredWPM,
        timeLimitMinutes: value.timeLimitMinutes,
        category: value.category,
        authority: value.authority,
        officialWebsite: value.officialWebsite
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    bilingual: null;
} | {
    english: null;
}): Variant_hindi_bilingual_english {
    return "hindi" in value ? Variant_hindi_bilingual_english.hindi : "bilingual" in value ? Variant_hindi_bilingual_english.bilingual : "english" in value ? Variant_hindi_bilingual_english.english : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exam>): Array<Exam> {
    return value.map((x)=>from_candid_Exam_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
